/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/bay.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bay(props) {
  const { nodes, materials } = useGLTF('../../bay.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.圓角2.geometry} material={materials.Steel} />
    </group>
  )
}

useGLTF.preload('../../bay.gltf')
